[package]
type = 'bash'
name = 'hookah'
slug = 'hookah'
version = '1.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'An elegantly minimal solution for Git hooks'

[run]
dependencies = ['https://github.com/hyperupcall/bash-core@v0.10.2', 'https://github.com/hyperupcall/bats-all@v4.4.0', 'https://github.com/hyperupcall/bash-term@v0.3.1', 'https://github.com/hyperupcall/bash-std@5c4775ea82173564e6422057e274749e58289400']
binDirs = []
sourceDirs = ['pkg/src/util', 'pkg/src/commands']
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
