[package]
type = 'bash'
name = 'hookah'
slug = 'hookah'
version = '0.3.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'An elegantly minimal solution for Git hooks'

[run]
dependencies = ['https://github.com/hyperupcall/bash-core.git@v0.3.2', 'https://github.com/hyperupcall/bats-all.git@v4.3.0']
binDirs = []
sourceDirs = ['pkg/src/util', 'pkg/src/commands']
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
